### ISSUE TITLE
PHPUnit failure 

### ISSUE THREAD

**Issue by junpataleta** [cperves/moodle-admin-cmdlinetools#1]
Hi, I ran PHP unit tests on your plugin and encountered the following failure:

> 1) tool_cmdlinetools_lib_testcase::test_cmdlinetools_hideshow_process
> Failed asserting that '1' matches expected false.
> 
> /home/jun/moodles/stable_master/moodle/admin/tool/cmdlinetools/tests/lib_test.php:43
> /home/jun/moodles/stable_master/moodle/lib/phpunit/classes/advanced_testcase.php:80
> 
> To re-run:
>  vendor/bin/phpunit tool_cmdlinetools_lib_testcase admin/tool/cmdlinetools/tests/lib_test.php
> 
> FAILURES!
> Tests: 1, Assertions: 2, Failures: 1.

**Comment by cperves** [comment]
As a matter of fact I have troubles with php unit test and command line process.
It never worked since I can't correctly pass php unit test environment to moodle cli commands
I never find the solution to that problem
So I'm gonna remove test directory unless you have a solution for this troubles

**Comment by cperves** [comment]
removed
