### ISSUE TITLE
set_config --check option not working.

### ISSUE THREAD

**Issue by junpataleta** [cperves/moodle-admin-cmdlinetools#2]
Hello, I tried running set_config and I was able to successfully set a configuration value. However, I tried using the --check option and I can't seem to make it work.

I suppose it should be used as something like below?

> php admin/tool/cmdlinetools/cli/cmdline_manager.php set_config --name=[configname] --check

Also, I am seeing the following notice when I try to use the --check option:

> Notice: Undefined variable: help in /home/jun/moodles/stable_master/moodle/admin/tool/cmdlinetools/classes/cmd/set_config_cli.php on line 38

**Comment by cperves** [comment]
as a matter of fact you need the required --value
But I have a trouble with check option.
I'm going to see that

**Comment by cperves** [comment]
I choose to correct that oldest cmdline cli and put name and value as required command line parameters instead of bad old option type.
check will then work

**Comment by cperves** [comment]
changed
