### ISSUE TITLE
cmdline_manager.php --help doesn't print out the list of commands available

### ISSUE THREAD

**Issue by junpataleta** [cperves/moodle-admin-cmdlinetools#3]
Hello,

I tried running 

> php admin/tool/cmdlinetools/cli/cmdline_manager.php --help
> but I am not getting the list of commands that are supported by the plugin.

The following is the output that I get on my console:

> command line tool to launch moodle commands :
> Usage :
>                 \$sudo -u www-data /usr/bin/php admin/cli/admin/tool/cmdlinetools/cli/cmdline_manager.php [argument]
> Argument(optional) : the name of a command to execute (listed bellow)
> {$a}
> 
> Options:
> -h, --help                 print out this help

**Comment by cperves** [comment]
corected
