### ISSUE TITLE
Normalize moodle component git repos names

### ISSUE THREAD

**Issue by vfremaux** [cperves/moodle-admin-cmdlinetools#4]
Hi Celine !

I was looking to your repos after activating following you. Some of them may not match the naming rules over which we will try to promote some better automation :

We usually agree in using moodle-&lt;frankenstylecomponentname&gt;, the frankenstylename is the name you are using in your version.php file.

For this repo, the normalized name would be : 
moodle-tool_cmdlinetools

normalisation can be usefull for who develop some automated integration processors that prefer rely on normalized names.

cheers !
Valery.

**Comment by cperves** [comment]
Thank a lot!

**Comment by cperves** [comment]
Change amde. Thank's a lot Valery
